server:
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: websocket-chatroom
  web:
    resources:
      static-locations: classpath:/static/
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.chatroom: DEBUG
    org.springframework.web.socket: DEBUG